name: test-windows
on: [push, pull_request]
jobs:
  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: src/github.com/k14s/ytt
    - name: Run Tests
      shell: powershell
      run: |
        cd \src\github.com\k14s\ytt
        .\hack\test-windows.ps1
